version: "3.3"
services:
    blueocean:
        container_name: jenkins-blueocean
        network_mode: jenkins
        environment:
            - DOCKER-HOST=tcp://docker:2376
        volumes:
            - ./jenkins-data:/var/jenkins_home
        ports:
            - 8080:8080
            - 50000:50000
        image: jenkinsci/blueocean
