import-module dism
get-appxpackage -allusers *BingWeather* | remove-appxpackage -allusers  
get-appxpackage -allusers *Xbox* | remove-appxpackage -allusers
get-appxpackage -allusers *Att* | remove-appxpackage -allusers
get-appxpackage -allusers *CandyCrush* | remove-appxpackage -allusers
get-appxpackage -allusers *Camera* | remove-appxpackage -allusers
get-appxpackage -allusers *news* | remove-appxpackage -allusers
get-appxpackage -allusers *EclipseManager* | remove-appxpackage -allusers
get-appxpackage -allusers *ActiproSoftwareLLC* | remove-appxpackage -allusers
get-appxpackage -allusers *Duolingo* | remove-appxpackage -allusers
get-appxpackage -allusers *3DViewer* | remove-appxpackage -allusers
get-appxpackage -allusers *Print3D* | remove-appxpackage -allusers
get-appxpackage -allusers *Wallet* | remove-appxpackage -allusers
get-appxpackage -allusers *CBSPreview* | remove-appxpackage -allusers
get-appxpackage -allusers *get* | remove-appxpackage -allusers
get-appxpackage -allusers *skype* | remove-appxpackage -allusers
get-appxpackage -allusers *oneconnect* | remove-appxpackage -allusers
get-appxpackage -allusers *office* | remove-appxpackage -allusers
get-appxpackage -allusers *camera* | remove-appxpackage -allusers
get-appxpackage -allusers *Bingnews* | remove-appxpackage -allusers
get-appxpackage -allusers *Messaging* | remove-appxpackage -allusers
get-appxpackage -allusers *OneNote* | remove-appxpackage -allusers
get-appxpackage -allusers *People* | remove-appxpackage -allusers
get-appxpackage -allusers *Photos* | remove-appxpackage -allusers
get-appxpackage -allusers *Alarms* | remove-appxpackage -allusers
get-appxpackage -allusers *Maps* | remove-appxpackage -allusers
get-appxpackage -allusers *Feedback* | remove-appxpackage -allusers
get-appxpackage -allusers *Zune* | remove-appxpackage -allusers
get-appxpackage -allusers *Solitaire* | remove-appxpackage -allusers
get-appxpackage -allusers *Solitaire* | remove-appxpackage -allusers
get-appxpackage -allusers *News* | remove-appxpackage -allusers
get-appxpackage -allusers *Lens* | remove-appxpackage -allusers
get-appxpackage -allusers *office* | remove-appxpackage -allusers
get-appxpackage -allusers *OfficeLens* | remove-appxpackage -allusers
Get-AppxPackage -allusers *xboxapp* | Remove-AppxPackage -allusers